services:
  nginx:
    image: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - back-end
    secrets:
      - ssl_cert
      - ssl_key
    restart: on-failure
  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    networks:
      - back-end
    restart: on-failure
  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    networks:
      - back-end
    restart: on-failure
networks:
    back-end:
secrets:
  ssl_cert:
    file: ../secrets/TODO.crt
  ssl_key:
    file: ../secrets/TODO.key 
