services:
  nginx:
    container_name: nginx-inception #dont do this for scaling with --scale nginx=3, but good for referencing it with a static name 
    environment: 
      - DOMAIN_NAME=${DOMAIN_NAME}
    image: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - frontend
    volumes:
      - wordpress_volume:/var/www/html
    restart: on-failure
    depends_on:
      - wordpress
  mariadb:
    container_name: mariadb-inception
    image: mariadb
    environment:
      - MARIADB_WP_USER=${MARIADB_WP_USER}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    build: ./requirements/mariadb
    networks:
      - backend
    restart: on-failure
    secrets:
      - mariadb_root_pw
      - mariadb_wp_user_pw
    volumes:
      - mariadb_volume:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -u root -p\"$(cat /run/secrets/mariadb_root_pw)\" || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
  wordpress:
    container_name: wordpress-inception
    image: wordpress
    build: ./requirements/wordpress
    networks:
      - backend
      - frontend
    restart: on-failure
    secrets:
      - mariadb_wp_user_pw
      - wordpress_admin_pw
      - wordpress_user_pw
    env_file: .env
    volumes:
      - wordpress_volume:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
networks:
    backend:
      driver: bridge
    frontend:
      driver: bridge

secrets:
  mariadb_root_pw:
    file: ../secrets/mariadb_root_pw.txt
  mariadb_wp_user_pw:
    file: ../secrets/mariadb_wp_user_pw.txt
  wordpress_admin_pw:
    file: ../secrets/wordpress_admin_pw.txt
  wordpress_user_pw:
    file: ../secrets/wordpress_user_pw.txt
  
volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER_LOGIN}/data/db
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER_LOGIN}/data/wp

    